// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: audit/v1/audit_service.proto

package auditv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AuditService_ListAuditLogsByUserID_FullMethodName   = "/audit.v1.AuditService/ListAuditLogsByUserID"
	AuditService_ListAuditLogsByEntityID_FullMethodName = "/audit.v1.AuditService/ListAuditLogsByEntityID"
)

// AuditServiceClient is the client API for AuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuditServiceClient interface {
	ListAuditLogsByUserID(ctx context.Context, in *ListAuditLogsByUserIDRequest, opts ...grpc.CallOption) (*ListAuditLogsByUserIDResponse, error)
	ListAuditLogsByEntityID(ctx context.Context, in *ListAuditLogsByEntityIDRequest, opts ...grpc.CallOption) (*ListAuditLogsByEntityIDResponse, error)
}

type auditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditServiceClient(cc grpc.ClientConnInterface) AuditServiceClient {
	return &auditServiceClient{cc}
}

func (c *auditServiceClient) ListAuditLogsByUserID(ctx context.Context, in *ListAuditLogsByUserIDRequest, opts ...grpc.CallOption) (*ListAuditLogsByUserIDResponse, error) {
	out := new(ListAuditLogsByUserIDResponse)
	err := c.cc.Invoke(ctx, AuditService_ListAuditLogsByUserID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) ListAuditLogsByEntityID(ctx context.Context, in *ListAuditLogsByEntityIDRequest, opts ...grpc.CallOption) (*ListAuditLogsByEntityIDResponse, error) {
	out := new(ListAuditLogsByEntityIDResponse)
	err := c.cc.Invoke(ctx, AuditService_ListAuditLogsByEntityID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditServiceServer is the server API for AuditService service.
// All implementations must embed UnimplementedAuditServiceServer
// for forward compatibility
type AuditServiceServer interface {
	ListAuditLogsByUserID(context.Context, *ListAuditLogsByUserIDRequest) (*ListAuditLogsByUserIDResponse, error)
	ListAuditLogsByEntityID(context.Context, *ListAuditLogsByEntityIDRequest) (*ListAuditLogsByEntityIDResponse, error)
	mustEmbedUnimplementedAuditServiceServer()
}

// UnimplementedAuditServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuditServiceServer struct {
}

func (UnimplementedAuditServiceServer) ListAuditLogsByUserID(context.Context, *ListAuditLogsByUserIDRequest) (*ListAuditLogsByUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAuditLogsByUserID not implemented")
}
func (UnimplementedAuditServiceServer) ListAuditLogsByEntityID(context.Context, *ListAuditLogsByEntityIDRequest) (*ListAuditLogsByEntityIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAuditLogsByEntityID not implemented")
}
func (UnimplementedAuditServiceServer) mustEmbedUnimplementedAuditServiceServer() {}

// UnsafeAuditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditServiceServer will
// result in compilation errors.
type UnsafeAuditServiceServer interface {
	mustEmbedUnimplementedAuditServiceServer()
}

func RegisterAuditServiceServer(s grpc.ServiceRegistrar, srv AuditServiceServer) {
	s.RegisterService(&AuditService_ServiceDesc, srv)
}

func _AuditService_ListAuditLogsByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditLogsByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).ListAuditLogsByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_ListAuditLogsByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).ListAuditLogsByUserID(ctx, req.(*ListAuditLogsByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_ListAuditLogsByEntityID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditLogsByEntityIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).ListAuditLogsByEntityID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_ListAuditLogsByEntityID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).ListAuditLogsByEntityID(ctx, req.(*ListAuditLogsByEntityIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditService_ServiceDesc is the grpc.ServiceDesc for AuditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audit.v1.AuditService",
	HandlerType: (*AuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAuditLogsByUserID",
			Handler:    _AuditService_ListAuditLogsByUserID_Handler,
		},
		{
			MethodName: "ListAuditLogsByEntityID",
			Handler:    _AuditService_ListAuditLogsByEntityID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "audit/v1/audit_service.proto",
}
